name: Test API MercadoLibre

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install tavily-python

      - name: Test API ML
        env:
          ML_CLIENT_ID: ${{ secrets.ML_CLIENT_ID }}
          ML_SECRET_KEY: ${{ secrets.ML_SECRET_KEY }}
          ML_REFRESH_TOKEN: ${{ secrets.ML_REFRESH_TOKEN }}
          TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
        run: python scraper_ml.py
